/*
Copyright 2026 bitkaio LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package resources

import (
	"testing"

	litellmv1alpha1 "github.com/PalenaAI/litellm-operator/api/v1alpha1"
)

// firstEndpoint extracts the single scrape endpoint from a generated
// ServiceMonitor, failing the test if the structure is not as expected.
func firstEndpoint(t *testing.T, sm map[string]interface{}) map[string]interface{} {
	t.Helper()
	spec, ok := sm["spec"].(map[string]interface{})
	if !ok {
		t.Fatalf("ServiceMonitor spec missing or wrong type: %#v", sm["spec"])
	}
	endpoints, ok := spec["endpoints"].([]interface{})
	if !ok || len(endpoints) != 1 {
		t.Fatalf("expected exactly one endpoint, got %#v", spec["endpoints"])
	}
	ep, ok := endpoints[0].(map[string]interface{})
	if !ok {
		t.Fatalf("endpoint wrong type: %#v", endpoints[0])
	}
	return ep
}

func TestBuildServiceMonitor_DisabledReturnsNil(t *testing.T) {
	instance := newTestInstance()
	// No observability config at all.
	if sm := BuildServiceMonitor(instance, map[string]string{"app": "litellm"}); sm != nil {
		t.Fatalf("expected nil ServiceMonitor when observability unset, got %#v", sm)
	}

	instance.Spec.Observability = &litellmv1alpha1.ObservabilitySpec{
		ServiceMonitor: &litellmv1alpha1.ServiceMonitorSpec{Enabled: false},
	}
	if sm := BuildServiceMonitor(instance, map[string]string{"app": "litellm"}); sm != nil {
		t.Fatalf("expected nil ServiceMonitor when disabled, got %#v", sm)
	}
}

func TestBuildServiceMonitor_DefaultsNoAuthorization(t *testing.T) {
	instance := newTestInstance()
	instance.Spec.Observability = &litellmv1alpha1.ObservabilitySpec{
		ServiceMonitor: &litellmv1alpha1.ServiceMonitorSpec{Enabled: true},
	}

	sm := BuildServiceMonitor(instance, map[string]string{"app": "litellm"})
	if sm == nil {
		t.Fatal("expected a ServiceMonitor, got nil")
	}
	ep := firstEndpoint(t, sm.Object)

	if ep["path"] != "/metrics" {
		t.Errorf("expected default path /metrics, got %v", ep["path"])
	}
	if ep["interval"] != "30s" {
		t.Errorf("expected default interval 30s, got %v", ep["interval"])
	}
	if _, ok := ep["authorization"]; ok {
		t.Errorf("expected no authorization block when unset, got %#v", ep["authorization"])
	}
}

func TestBuildServiceMonitor_CustomPath(t *testing.T) {
	instance := newTestInstance()
	instance.Spec.Observability = &litellmv1alpha1.ObservabilitySpec{
		ServiceMonitor: &litellmv1alpha1.ServiceMonitorSpec{
			Enabled: true,
			Path:    "/metrics/",
		},
	}

	ep := firstEndpoint(t, BuildServiceMonitor(instance, map[string]string{"app": "litellm"}).Object)
	if ep["path"] != "/metrics/" {
		t.Errorf("expected custom path /metrics/, got %v", ep["path"])
	}
}

// When authorization is requested without explicit credentials, the operator
// must fall back to the instance's master key Secret so the reporter's
// authenticated /metrics endpoint can be scraped without restating the key.
func TestBuildServiceMonitor_AuthorizationDefaultsToMasterKeySecretRef(t *testing.T) {
	instance := newTestInstance() // master key via secretRef "master-key-secret"/"key"
	instance.Spec.Observability = &litellmv1alpha1.ObservabilitySpec{
		ServiceMonitor: &litellmv1alpha1.ServiceMonitorSpec{
			Enabled:       true,
			Authorization: &litellmv1alpha1.ServiceMonitorAuthorization{},
		},
	}

	ep := firstEndpoint(t, BuildServiceMonitor(instance, map[string]string{"app": "litellm"}).Object)
	auth, ok := ep["authorization"].(map[string]interface{})
	if !ok {
		t.Fatalf("expected authorization block, got %#v", ep["authorization"])
	}
	if auth["type"] != "Bearer" {
		t.Errorf("expected default type Bearer, got %v", auth["type"])
	}
	creds, ok := auth["credentials"].(map[string]interface{})
	if !ok {
		t.Fatalf("expected credentials block, got %#v", auth["credentials"])
	}
	if creds["name"] != "master-key-secret" || creds["key"] != "key" {
		t.Errorf("expected master key secretRef credentials, got name=%v key=%v", creds["name"], creds["key"])
	}
}

// With an auto-generated master key (no secretRef), authorization must default
// to the operator-created "<instance>-master-key" Secret.
func TestBuildServiceMonitor_AuthorizationDefaultsToAutoGeneratedSecret(t *testing.T) {
	instance := newTestInstance()
	instance.Spec.MasterKey = litellmv1alpha1.MasterKeySpec{AutoGenerate: true}
	instance.Spec.Observability = &litellmv1alpha1.ObservabilitySpec{
		ServiceMonitor: &litellmv1alpha1.ServiceMonitorSpec{
			Enabled:       true,
			Authorization: &litellmv1alpha1.ServiceMonitorAuthorization{},
		},
	}

	ep := firstEndpoint(t, BuildServiceMonitor(instance, map[string]string{"app": "litellm"}).Object)
	creds := ep["authorization"].(map[string]interface{})["credentials"].(map[string]interface{})
	if creds["name"] != "test-instance-master-key" || creds["key"] != "master-key" {
		t.Errorf("expected auto-generated master key Secret, got name=%v key=%v", creds["name"], creds["key"])
	}
}

// An explicit credentials override must win over the master key default, and a
// custom type must be preserved.
func TestBuildServiceMonitor_AuthorizationExplicitCredentials(t *testing.T) {
	instance := newTestInstance()
	instance.Spec.Observability = &litellmv1alpha1.ObservabilitySpec{
		ServiceMonitor: &litellmv1alpha1.ServiceMonitorSpec{
			Enabled: true,
			Authorization: &litellmv1alpha1.ServiceMonitorAuthorization{
				Type: "Bearer",
				Credentials: &litellmv1alpha1.SecretKeyRef{
					Name: "litellm-masterkey",
					Key:  "masterkey",
				},
			},
		},
	}

	ep := firstEndpoint(t, BuildServiceMonitor(instance, map[string]string{"app": "litellm"}).Object)
	creds := ep["authorization"].(map[string]interface{})["credentials"].(map[string]interface{})
	if creds["name"] != "litellm-masterkey" || creds["key"] != "masterkey" {
		t.Errorf("expected explicit credentials to win, got name=%v key=%v", creds["name"], creds["key"])
	}
}
